name: Test StaFip compiler
on:
  push:

jobs:
  run-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make verify.sh executable
        run: chmod +x ./verify_stafip.sh

      - name: Run verify script
        run: ./verify_stafip.sh
