name: Test StaFip compiler
on:
  push:

jobs:
  run-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make verify_stafip.sh executable
        run: chmod +x ./verify_stafip.sh

      - name: Install LLVM (clang & llc)
        run: |
          sudo apt update
          sudo apt install -y clang llvm

      - name: Make banchmarks_utils/compile_stafip_scripts_in.sh executable
        run: chmod +x ./banchmarks_utils/compile_stafip_scripts_in.sh

      - name: Run verify script
        # run: ./verify_stafip.sh
        run: cmake . && cmake --build . && ./stud-main/cecko5 -a ./DebugLog.txt ./test/finger_trees_fip.ffip
